config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks
  devise_for :users

  root 'user_tasks#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]
  before_action :all_tasks, only: [:index, :create, :update, :destroy]


  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.create(user_task_params)
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    @user_task.update(user_task_params)
  end

  def destroy
    @user_task.destroy
  end

  private

    def all_tasks
      @user_tasks = UserTask.order("due")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Task App via Rails Composer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Task App via Rails Composer" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
      <div class="container-fluid">
           <%= render 'layouts/messages' %>

           <%= yield %>

       </div><!--container-fluid-->
    </main>

  </body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function(){
  $('#user_task_due input').datepicker({
    autoclose: true,
    todayHighlight: true,
    toggleActive: true,
    format: "yyyy-mm-dd",
    orientation: "top auto"
  }); //sandbox-container
}); //(document).ready

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, placeholder: "Make the Bed" %>
    <%= f.input :due, as: :string, placeholder: "Click to Select Date" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<div class="well well-sm">
  <span class="task">
    <%= link_to user_task.description, user_task, remote: true, method: :delete, data: { confirm: 'PEW! PEW! PEW! Obliterate this task from your list!... Right?'} %>
  </span>
  
  <span class="pull-right">
    <%= user_task.due %>
    <%= link_to edit_user_task_path(user_task), remote: true do %>
    <%= fa_icon 'pencil' %>
  <% end %>
  </span>

</div>

app/views/user_tasks/cancel.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/create.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");
$('#task-form').slideUp(850);

app/views/user_tasks/destroy.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(550);

<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Tasks</h1>
    <h2>Practice app built via rails composer and working via javascript</h2>
  </div><!--col-sm-12-->
</div><!--row-->

<div class="row">
  <div class="col-sm-4">

      <%= link_to new_user_task_path, remote: true do %>
        <button class="btn btn-default add-task"><%= fa_icon "plus" %> Add Task</button>
      <% end %>

    <div id="task-form"></div><!--form will be placed in here-->

  </div><!--col-sm-4-->

  <div class="col-sm-8">
    <div id="tasks">
      <ul>
      <%= render @user_tasks %>
      </ul>


    </div><!--tasks-->
  </div><!--col-sm-8-->

</div><!--row-->

    

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(550);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");
$('#task-form').slideUp(550);